version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: workhub
      POSTGRES_PASSWORD: workhub123
      POSTGRES_DB: workhub
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://workhub:workhub123@db:5432/workhub
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=development-secret-key-change-in-production
    depends_on:
      - db
      - redis
    volumes:
      - ./app:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data: